export const types = {
    SET_LIVES_FIRST_PLAYER: 'SET_LIVES_FIRST_PLAYER',
    SET_LIVES_SECOND_PLAYER: 'SET_LIVES_SECOND_PLAYER',
    FIRST_PLAYER_ADD_ITEM: 'FIRST_PLAYER_ADD_ITEM',
    SECOND_PLAYER_ADD_ITEM: 'SECOND_PLAYER_ADD_ITEM',
    FIRST_PLAYER_REMOVE_ITEM: 'FIRST_PLAYER_REMOVE_ITEM',
    SECOND_PLAYER_REMOVE_ITEM: 'SECOND_PLAYER_REMOVE_ITEM',
    SET_ETHER_FIRST_PLAYER: 'SET_ETHER_FIRST_PLAYER',
    SET_ETHER_SECOND_PLAYER: 'SET_ETHER_SECOND_PLAYER',
    RESET_ITEMS: 'RESET_ITEMS'
}